[package]
name = "faas-wasm-runtime-image"
version = "0.1.0"
authors = ["Daniel Bevenius <daniel.bevenius@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmi = "0.4.0"
hyper = "0.11.7"
futures = "0.1.17"
